name: Build and Push
on: 
  push:

jobs:
  docker_build_tag_push:
    runs-on: ubuntu-latest
    name: Docker Build, Tag & Push
    steps:
        - uses: actions/checkout@v3
          name: Check out code
      
        - uses: mr-smithers-excellent/docker-build-push@v6
          name: Build & push Docker image
          with:
            image: kdua1/flower-image
            tags: v1, latest
            registry: docker.io
            dockerfile: Dockerfile
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - uses: mr-smithers-excellent/docker-build-push@v3

        - name: Configure AWS Credentials 
          uses: aws -actions/configure-aws-credentias@v1
          with:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1

        - name: Login to Amzon ECR
          id: login-ecr
          uses: aws-action/amazon-ecr-login@v1
        - name: Buid, tag, and push image to Amazon ECR
          env: 
            ECR_REGISTORY: ${{ steps.login-ecr.output.registory }}
            ECR_REPOSITORY: ecr-web-repo
            IMAGE_TAG: ${{ github.sha }}
            registry: 546752724724.dkr.ecr.us-east-1.amazonaws.com
          run: 
            decker build -t $ECR_REGISTORY/$ECR_REPOSITORY:$IMAGE_TAG .
            docker push $ECR_REGISTORY/$ECR_REPOSITORY:$IMAGE_TAG
           